### PR TITLE
New tests for contact form mailer exceptions and limits for CRI admin

### PR DESCRIPTION
**Pull request by damirius**

### CODE REVIEW

**Comment by damirius** [comment]
@WebDevJL 

This should be it. Can be tricky sometimes to get all those lines in the end, there are always few cases where is harder to get hits on exact lines but this should do it.

**Comment by WebDevJL** [comment]
@damirius I think that if we can't unit test some code, there is maybe an
issue in the conception. As we code, the apps will get bigger and bigger.
Do you best so that unit testing is easy.

However we will surely hit a usecase that will be a pain or impossible to
test. But is mocking not a way to test abstract code?

## 

Jérémie Litzer
Puzzlout

**Comment by damirius** [comment]
@WebDevJL 

Unit testing is often easy, functional testing is little trickier. Mocking is answer to most things, but it can be tricky to test something even with mocking. Every service outside the controller is mocked, especially since we use api calls, everything returned is mocked, mailer is mocked as well as many other services we use in our controllers

**Comment by WebDevJL** [comment]
@damirius mocks are what we expect, if I am correct. So if we can test
through them the code of our controllers, we can be sure that if an error
happens, it is something that the controllers received that wasn't expected.

So far, you did a good job to test the application. I haven't dive into the
code to find the  scenario that might have slipped through your finger but
I trust and know that you did a great job far.

Let's continue!

## 

Jérémie Litzer
Puzzlout

**Pull request merged**
